services:
  kabu:
    build: .
    image: kabu_img
    container_name: kabu_ctr
    working_dir: /src
    tty: true
    ports:
      - 5007:8080
    volumes:
      - ./src:/src
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  db:
    volumes:
      - ./docker-mysql/DB:/docker-entrypoint-initdb.d
      - ./docker-mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 5010:3306
    image: mysql:8.0.36-debian
    container_name: kabu_db
    tty: true
    environment:
      - MYSQL_DATABASE=travel_db
      - MYSQL_USER=kabu-user
      - MYSQL_PASSWORD=kabu-pass-2025
      - MYSQL_ROOT_PASSWORD=root_password
    command: mysqld
